getMockData = function(adata, Nd=1000, af_null=NULL, outdir=NULL, BGZIP="bgzip", BCFTOOLS="bcftools", ncore=max(1, parallel::detectCores()-1)){
    
    k = simulate_king(Nd)
    uiid = k$iid
    x = simulate_x_from_xlist(split(adata$x, adata$iid), Nd, iid=uiid)
    
    pc = data.frame(pc1=rnorm(Nd),pc2=rnorm(Nd))[match(x$IID,uiid),]
    sex = c("F","M")[(runif(Nd)>0.5)+1][match(x$IID,uiid)]
    
    x=cbind(x,y=rep(0,nrow(x)))
    adata2 = getData(x, Cov=cbind(pc,sex), king=k$king, inducing_points=adata$ta)
    
    iid = adata2$iid
    fid = adata2$fid
    N = adata2$N
    M = adata$M
    ta = adata$ta
    rho = adata$rho
    beta0 = c(adata$PhiXty[1], 0.01, 0.01, 0.01, 0.01, tail(adata$PhiXty,M))
    Knm = getK(adata2$x, ta, rho)
    Kmm = getK(ta, ta, rho)
    R = chol(Kmm)
    tKnm = t(forwardsolve(t(R),t(Knm)))
    adata2$delta2 = c(10,0.01,0.01,0.01)
    delta2d = adata$delta2d
    sigma2 = adata$sigma2
    
    Lmat = adata2$Lmat[match(iid, unique(iid)),]
    if(sum(Lmat$IID == iid) != length(iid)){
        return("Lmat is inappropriate!")
    }else{
        Lmat = as.matrix(Lmat[,-c(1:2)])
    }
    
    ufid = unique(fid)
    fid_fac = factor(fid, levels=ufid)
    idx_list = split(seq_len(N), fid_fac)
    one_id_fun = function(ii){
        n1 = length(unique(iid[ii]))
        tk = c1prior = NULL
        for(j in 1:n1){
            tk = cbind(tk, cbind(tKnm[ii,,drop=FALSE], 1) * Lmat[ii,j])
            c1prior = c(c1prior, rep(delta2d, c(M,1)))
        }
        c(tk%*%rnorm(n1*(M+1),0,sqrt(c1prior)))
    }
    tmp = try(
        unlist(parallel::mclapply(idx_list, one_id_fun, mc.cores=ncore))
    )
    
    # genotype effect
    pgs = 0
    if(!is.null(adata$Beta)&!is.null(adata$allele_frequency)){
        G=simGeno(adata2, af=adata$allele_frequency)
        Gstar = G-adata$allele_frequency*2
        adata2$G_under_alt = G
        for(l in seq(nrow(adata$Beta))){
            pgs = pgs + c(cbind(tKnm, 1)%*%adata$Beta[l,])*Gstar[l,match(adata2$iid,adata2$Lmat[,2])]
        }
    }
    adata2$y = cbind(adata2$X, tKnm)%*%beta0 + tmp + rnorm(N,0,sqrt(sigma2)) + pgs
    if(!is.null(af_null)){
        G = simGeno(adata2, af=af_null)
        adata2$G_under_null = G
    }
    if(!is.null(outdir)){
        write.table(data.frame(IID=adata2$iid, x=adata2$x, y=adata2$y), col=T,row=F,sep="\t",quote=F,file=paste(outdir, "/input.tsv",sep=""))
        write.table(data.frame(pc,sex), col=T,row=F,sep="\t",quote=F,file=paste(outdir, "/covariates.tsv",sep=""))
        write.table(k, col=T,row=F,sep="\t",quote=F,file=paste(outdir, "/king.kin0",sep=""))
        writeDoseToVCF(rbind(adata2$G_under_null,adata2$G_under_alt),
            paste(outdir, "/dose.vcf.gz",sep=""), BGZIP=BGZIP, BCFTOOLS=BCFTOOLS, index=TURE)
    }
    
    
    invisible(adata2)
}


#' Simulate genotypes from allele frequencies using the relatedness structure
#'
#' `simGeno()` simulates genotype dosages from given allele frequencies using
#' the family-wise Cholesky representation stored in a `DynamicPGS` object. The
#' simulated genotypes approximately follow Hardy-Weinberg proportions at each
#' variant while preserving the relatedness structure encoded in `adata$Lmat`.
#'
#' @param adata A `DynamicPGS` object returned by `getData()`. The object must
#'   contain `Lmat`, which stores family IDs, individual IDs, and the left-aligned
#'   Cholesky representation of the additive relationship matrix.
#' @param af Numeric vector of allele frequencies. Values must be finite and
#'   strictly between 0 and 1. The names of `af`, if present, are ignored. Variant
#'   IDs in the returned matrix are generated as `chr0:1:A:C`, `chr0:2:A:C`, and
#'   so on.
#' @param seed Optional integer seed for reproducible simulation.
#' @param id_col Character. Column name in `adata$Lmat` containing individual IDs.
#'   Default is `"IID"`.
#' @param fid_col Character. Column name in `adata$Lmat` containing family IDs.
#'   Default is `"FID"`.
#'
#' @return A numeric genotype dosage matrix with variants in rows and individuals
#'   in columns. Entries are coded as 0, 1, or 2 copies of the effect allele.
#'   Row names are generated as `chr0:<index>:A:C`, and column names are taken
#'   from the individual IDs in `adata$Lmat`.
#'
#' @details
#' For each variant with allele frequency `p`, genotypes are generated by
#' thresholding correlated standard normal variables so that the marginal
#' genotype probabilities approximately follow Hardy-Weinberg proportions:
#' `Pr(G = 0) = (1 - p)^2`, `Pr(G = 1) = 2p(1 - p)`, and `Pr(G = 2) = p^2`.
#'
#' Correlation among related individuals is induced by the Cholesky factors stored
#' in `adata$Lmat`. This provides an approximate relatedness-preserving genotype
#' simulation. It is not an exact Mendelian segregation simulator and does not
#' model haplotypes, linkage disequilibrium, or parental transmission explicitly.
#'
#' @examples
#' \dontrun{
#' adata <- getData(Data = phenotype_table, king = king_table)
#' af <- c(0.10, 0.25, 0.40)
#' G <- simGeno(adata, af, seed = 1)
#' dim(G)
#' rownames(G)
#' G[, 1:5]
#' }
#'
#' @export
simGeno <- function(adata, af, seed=NULL, id_col="IID", fid_col="FID"){
    Lmat <- adata$Lmat
    if(!is.null(seed)) set.seed(seed)
    stopifnot(id_col %in% colnames(Lmat), fid_col %in% colnames(Lmat))
    af <- as.numeric(af)
    if(any(!is.finite(af) | af <= 0 | af >= 1)) stop("af must be finite and between 0 and 1.")
    
    iid <- as.character(Lmat[[id_col]])
    fid <- as.character(Lmat[[fid_col]])
    L <- as.matrix(Lmat[, setdiff(colnames(Lmat), c(fid_col, id_col)), drop=FALSE])
    N <- nrow(L)
    V <- length(af)
    
    variant_id <- paste0("chr0:", seq_len(V), ":A:C")
    G <- matrix(NA_real_, nrow=V, ncol=N, dimnames=list(variant_id, iid))
    idx_list <- split(seq_len(N), factor(fid, levels=unique(fid)))
    
    q0 <- qnorm((1 - af)^2)
    q1 <- qnorm((1 - af)^2 + 2 * af * (1 - af))
    
    for(ii in idx_list){
        m <- length(ii)
        Lb <- L[ii, seq_len(m), drop=FALSE]
        Z <- Lb %*% matrix(rnorm(m * V), nrow=m, ncol=V)
        G[, ii] <- t((Z > matrix(q0, m, V, byrow=TRUE)) + (Z > matrix(q1, m, V, byrow=TRUE)))
    }
    G
}


simulate_king <- function(N=1000, max_3rd_degree_size=3, seed=1){
    set.seed(seed)
    iid <- sprintf("ID%06d", seq_len(N))
    fid <- sprintf("F%06d", seq_len(N))

    kin_range <- list(
        PO  = c(0.1768, 0.3536),   # parent-offspring / duplicate-ish upper avoided
        FS  = c(0.1768, 0.3536),   # full siblings
        S2  = c(0.0884, 0.1768),   # second-degree
        S3  = c(0.0442, 0.0884)    # third-degree
    )

    res <- list()
    used <- rep(FALSE, N)
    k <- 1

    while(any(!used)){
        avail <- which(!used)
        m <- sample(seq_len(max_3rd_degree_size), 1)
        m <- min(m, length(avail))
        members <- sample(avail, m)
        used[members] <- TRUE

        if(m >= 2){
            pairs <- t(combn(members, 2))
            keep <- runif(nrow(pairs)) < runif(1, 0.4, 0.9)
            pairs <- pairs[keep,,drop=FALSE]

            if(nrow(pairs) > 0){
                deg <- sample(c("PO","FS","S2","S3"), nrow(pairs), replace=TRUE, prob=c(0.15,0.20,0.30,0.35))
                kin <- mapply(function(d) runif(1, kin_range[[d]][1], kin_range[[d]][2]), deg)
                ibs0 <- ifelse(deg=="PO", 0,
                         ifelse(deg=="FS", runif(length(deg),0.001,0.01),
                         ifelse(deg=="S2", runif(length(deg),0.005,0.03),
                                        runif(length(deg),0.01,0.05))))
                hethet <- runif(length(deg), 0.08, 0.18)
                ibs0_seg <- runif(length(deg), 0, 0.02)

                res[[k]] <- data.frame(
                    FID1=fid[pairs[,1]], ID1=iid[pairs[,1]],
                    FID2=fid[pairs[,2]], ID2=iid[pairs[,2]],
                    N_SNP=sample(500000:700000, nrow(pairs), replace=TRUE),
                    HetHet=hethet,
                    IBS0=ibs0,
                    Kinship=kin,
                    Error=0,
                    stringsAsFactors=FALSE
                )
                k <- k+1
            }
        }
    }

    kin0 <- if(length(res)) do.call(rbind, res) else data.frame()
    kin0 <- kin0[kin0$Kinship >= 0.0442,,drop=FALSE]
    rownames(kin0) <- NULL
    list(king=kin0, iid=iid)
}

simulate_x_from_xlist <- function(xlist, N=1000, iid=NULL, seed=1, jitter=0, round_digits=1){
    set.seed(seed)
    xlist <- lapply(xlist, function(z) sort(round(as.numeric(z[is.finite(z)]), round_digits)))
    xlist <- xlist[lengths(xlist) > 0]
    if(length(xlist)==0) stop("xlist has no valid month-age vectors")
    if(is.null(iid)) iid <- sprintf("SIM%06d", seq_len(N))
    if(length(iid) != N) stop("length(iid) must be equal to N")
    out <- lapply(iid, function(id){
        x <- sample(xlist, 1)[[1]]
        if(jitter > 0) x <- pmax(0, x + rnorm(length(x), 0, jitter))
        data.frame(IID=id, x=x)
    })
    out <- do.call(rbind, out); 
    rownames(out) <- NULL;
    out
}





#' Write a dosage matrix to a VCF file
#'
#' `writeDoseToVCF()` writes a numeric dosage matrix to a minimal VCF file with
#' `FORMAT/DS` entries. The matrix is assumed to contain alternate-allele dosages,
#' with variants in rows and samples in columns.
#'
#' Variant information is taken from `variant_info` if supplied, otherwise from
#' `attr(dose, "variant_info")`, and finally from `rownames(dose)`. Row names must
#' be in the form `CHR:POS:REF:ALT`, for example `"chr1:12345:A:G"`.
#'
#' @param dose Numeric matrix or matrix-like object. Rows are variants and columns
#'   are samples. Column names are used as VCF sample IDs.
#' @param outfile Character scalar. Output VCF path. If the filename ends with
#'   `.gz`, the output is bgzip-compressed using `BGZIP`.
#' @param variant_info Optional data frame containing variant metadata. It must
#'   contain columns `CHR`, `POS`, `REF`, and `ALT`, and have the same number of
#'   rows as `dose`. If `NULL`, `attr(dose, "variant_info")` is used when
#'   available; otherwise `rownames(dose)` are parsed as `CHR:POS:REF:ALT`.
#' @param digits Integer. Number of digits after the decimal point used when
#'   writing dosage values.
#' @param sort Logical. If `TRUE`, variants are sorted by chromosome, position,
#'   reference allele, and alternate allele before writing.
#' @param id Character scalar or vector. Value written to the VCF `ID` column. If
#'   length one, the same value is used for all variants. If a vector, it must have
#'   length equal to the number of variants.
#' @param BGZIP Character scalar. Path to the `bgzip` executable, or command name
#'   if `bgzip` is available in the system `PATH`.
#' @param BCFTOOLS Character scalar. Path to the `bcftools` executable, or command
#'   name if `bcftools` is available in the system `PATH`.
#' @param index Logical. If `TRUE`, create a tabix index for the bgzip-compressed
#'   VCF using `bcftools index -t -f`.
#' @param progress Logical. If `TRUE`, show a progress bar while writing variants.
#'
#' @return Invisibly returns `outfile`.
#'
#' @details
#' This function writes a minimal VCF containing only the `DS` FORMAT field. It
#' does not write `GT`, genotype probabilities, INFO fields, or contig header
#' lines. Missing or non-finite dosage values are written as `"."`.
#'
#' The output dosage values are not rounded to hard genotypes and are not clipped
#' to the interval `[0, 2]`.
#'
#' @examples
#' \dontrun{
#' variants <- c("chr1:12345:A:G", "chr1:67890:C:T")
#' samples <- c("ID001", "ID002", "ID003")
#' D <- matrix(c(0.1, 1.2, 2.0, 0.0, NA, 1.7), nrow=2, byrow=TRUE)
#' rownames(D) <- variants
#' colnames(D) <- samples
#'
#' writeDoseToVCF(D, "dose.vcf")
#'
#' writeDoseToVCF(
#'   D,
#'   "dose.vcf.gz",
#'   BGZIP = "bgzip",
#'   BCFTOOLS = "bcftools",
#'   index = TRUE
#' )
#' }
#'
#' @export
writeDoseToVCF = function(dose, outfile, variant_info=NULL, digits=4, sort=TRUE, id=".", BGZIP="bgzip", BCFTOOLS="bcftools", index=TURE, progress=TRUE){
    if(is.null(dim(dose))) stop("'dose' must be a matrix-like object.")
    dose = as.matrix(dose)
    if(is.null(colnames(dose))) colnames(dose) = paste0("S", seq_len(ncol(dose)))
    sample_ids = colnames(dose)

    if(is.null(variant_info)) variant_info = attr(dose, "variant_info")
    if(!is.null(variant_info) && all(c("CHR","POS","REF","ALT") %in% colnames(variant_info))){
        vi = as.data.frame(variant_info, stringsAsFactors=FALSE)
        if(nrow(vi) != nrow(dose)) stop("'variant_info' must have the same number of rows as 'dose'.")
        vi$CHR = as.character(vi$CHR); vi$POS = as.integer(vi$POS)
        vi$REF = as.character(vi$REF); vi$ALT = as.character(vi$ALT)
    }else{
        if(is.null(rownames(dose))) stop("Either rownames(dose) as CHR:POS:REF:ALT or 'variant_info' is required.")
        sp = strsplit(rownames(dose), ":", fixed=TRUE)
        if(any(lengths(sp) != 4)) stop("rownames(dose) must be in CHR:POS:REF:ALT format.")
        vi = data.frame(CHR=sapply(sp, `[`, 1), POS=as.integer(sapply(sp, `[`, 2)), REF=sapply(sp, `[`, 3), ALT=sapply(sp, `[`, 4), stringsAsFactors=FALSE)
    }
    if(any(is.na(vi$POS))) stop("POS must be integer.")

    if(length(id)==1L) id = rep(id, nrow(dose))
    if(length(id) != nrow(dose)) stop("'id' must have length 1 or nrow(dose).")
    id = as.character(id)

    chr_rank = function(x){
        y = sub("^chr", "", x, ignore.case=TRUE)
        z = match(y, c(as.character(1:22), "X", "Y", "XY", "MT", "M"))
        z[is.na(z)] = 1000 + match(y[is.na(z)], unique(y[is.na(z)]))
        z
    }

    if(sort){
        o = order(chr_rank(vi$CHR), vi$POS, vi$REF, vi$ALT)
        vi = vi[o,,drop=FALSE]
        dose = dose[o,,drop=FALSE]
        id = id[o]
    }

    compress = grepl("\\.gz$", outfile)
    con = if(compress) pipe(paste(shQuote(BGZIP), "-c >", shQuote(outfile)), open="w") else file(outfile, open="w")
    closed = FALSE
    pb = NULL
    on.exit({
        if(!closed) try(close(con), silent=TRUE)
        if(!is.null(pb)) try(close(pb), silent=TRUE)
    }, add=TRUE)

    header = c(
        "##fileformat=VCFv4.2",
        "##source=DynamicPGS",
        "##FORMAT=<ID=DS,Number=1,Type=Float,Description=\"Estimated alternate allele dosage\">",
        paste(c("#CHROM","POS","ID","REF","ALT","QUAL","FILTER","INFO","FORMAT",sample_ids), collapse="\t")
    )
    writeLines(header, con)

    fmt_ds = function(x){
        y = rep(".", length(x))
        ok = is.finite(x)
        y[ok] = formatC(x[ok], format="f", digits=digits)
        y
    }

    if(progress) pb = utils::txtProgressBar(min=0, max=nrow(dose), style=3)
    for(i in seq_len(nrow(dose))){
        line = paste(c(vi$CHR[i], vi$POS[i], id[i], vi$REF[i], vi$ALT[i], ".", "PASS", ".", "DS", fmt_ds(dose[i,])), collapse="\t")
        writeLines(line, con)
        if(progress) utils::setTxtProgressBar(pb, i)
    }
    if(!is.null(pb)){ close(pb); pb = NULL }

    status = close(con)
    closed = TRUE
    if(!is.null(status) && length(status)>0 && !is.na(status) && status!=0) stop("Failed to write VCF.")

    if(index){
        if(!compress) stop("index=TRUE requires bgzip-compressed output, e.g. outfile='out.vcf.gz'.")
        st = system2(BCFTOOLS, c("index","-t","-f",outfile))
        if(!is.null(st) && st != 0) stop("bcftools index failed.")
    }

    invisible(outfile)
}
